// Auto-generated by output\merge_offsets.ps1 - do not edit by hand.
// Roblox Version: version-4310300497aa4917
// In-process offsets mirroring src/sdk/offsets.h (subset the native chams renderer needs).
#pragma once
#include <cstdint>

namespace nofs {
namespace VisualEngine {
    inline constexpr uintptr_t Pointer    = 0x846F768;
    inline constexpr uintptr_t ViewMatrix = 0x1B0;
}
namespace FakeDataModel {
    inline constexpr uintptr_t Pointer       = 0x8E42C98;
    inline constexpr uintptr_t RealDataModel = 0x1F8;
}
namespace Players {
    inline constexpr uintptr_t LocalPlayer = 0x130;
}
namespace BasePart {
    inline constexpr uintptr_t Primitive = 0x188;
    inline constexpr uintptr_t Massless  = 0x137;
}
namespace Primitive {
    inline constexpr uintptr_t Frame = 0xB0; // 48-byte CFrame (rot r[9] + pos)
    inline constexpr uintptr_t Size  = 0x1C4;
}
} // namespace nofs
